name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Set up python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies.
        run: pip install sly llvmlite packaging

      - name: Build compiler.
        run: |
          python main.py main.div
          ren main.exe divine.exe

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: compiler
          path: divine.exe