name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Set up python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install sly

      - name: Set up LLVM toolchain.
        run: |
          choco install llvm -y
          echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH

      - name: Build compiler.
        run: |
          python main.py main.div
          ren main.exe divine.exe

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          path: divine.exe